# Build & push your Dockerfile image to Artifact Registry
substitutions:
  _REGION: us-west1
  _REPO: citizenscience-artifact-repository
  _SERVICE: citizenscience-app-${BRANCH_NAME}

steps:
  # Build
  - name: maven:3.9-eclipse-temurin-21
    args:
      - -Pproduction
      - -B
      - -q
      - -DskipTests
      - -Djib.to.image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}
      - -Djib.to.tags=$COMMIT_SHA,$BRANCH_NAME
      - clean
      - compile
      - com.google.cloud.tools:jib-maven-plugin:build

  # Deploy to Cloud Run right after push
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE}
      - --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$BRANCH_NAME
      - --region=${_REGION}
      - --project=$PROJECT_ID

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$COMMIT_SHA
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$BRANCH_NAME

options:
  logging: CLOUD_LOGGING_ONLY